-- db/changelog/changes/01-create-budget-table.sql
--liquibase formatted sql

--changeset teamfourpixels:1
CREATE TABLE budgets (
id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
user_id BIGINT NOT NULL,
year INT NOT NULL,
month INT NOT NULL,
total_income DECIMAL(19, 2) NOT NULL
);