-- db/changelog/changes/02-create-category-table.sql
--liquibase formatted sql

--changeset teamfourpixels:2
CREATE TABLE categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    name VARCHAR(255) UNIQUE NOT NULL,
    is_system BOOLEAN NOT NULL DEFAULT FALSE
);