CREATE TABLE budget_limits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    budget_id BIGINT NOT NULL,
    category_id BIGINT NOT NULL,

    limit_value DECIMAL(19, 2) NOT NULL,

    limit_type VARCHAR(10) NOT NULL,

    CONSTRAINT fk_budget_limit_budget
        FOREIGN KEY (budget_id)
        REFERENCES budgets (id),
    CONSTRAINT fk_budget_limit_category
        FOREIGN KEY (category_id)
        REFERENCES categories (id)
);