CREATE TABLE transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    transaction_time TIMESTAMP WITH TIME ZONE NOT NULL,
    amount DECIMAL(19, 2) NOT NULL,
    type VARCHAR(10) NOT NULL,
    mcc VARCHAR(4),
    merchant VARCHAR(255),
    category_id BIGINT NOT NULL,
    description VARCHAR(500),
    bank_transaction_ref_id VARCHAR(100) UNIQUE
);

CREATE INDEX idx_transactions_user_time ON transactions (user_id, transaction_time DESC);
CREATE INDEX idx_transactions_bank_ref ON transactions (bank_transaction_ref_id);