CREATE TABLE categorization_rules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    keyword VARCHAR(255) NOT NULL,
    category_id BIGINT NOT NULL
);

CREATE INDEX idx_rules_user_id ON categorization_rules (user_id);