server:
  port: 8081

spring:
  application:
    name: budget-service
  datasource:
    url: jdbc:postgresql://db:5432/smartbudget
    username: postgres
    password: 12345
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: true

jwt:
  secret: secret-key
  expiration: 3600000

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    liquibase: INFO