server:
  port: 8081

spring:
  application:
    name: core
  datasource:
    url: jdbc:postgresql://db:5432/smartbudget
    username: postgres
    password: 12345
  jpa:
    show-sql: true

jwt:
  secret: ${JWT_SECRET}
  expiration: 3600000