name: CI & API Tests

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
      - main

jobs:
  api_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 21 and Cache Maven Dependencies
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build Project
        run: mvn -B package -DskipTests -q

      - name: Create .env file for Docker
        run: |
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "DB_USER=${{ secrets.DB_USER }}" >> .env
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
          echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
          echo "JWT_EXPIRATION=${{ secrets.JWT_EXPIRATION }}" >> .env
          echo "AUTH_PORT=${{ secrets.AUTH_PORT }}" >> .env
          echo "BUDGET_PORT=${{ secrets.BUDGET_PORT }}" >> .env
          echo "TRANSACTION_PORT=${{ secrets.TRANSACTION_PORT }}" >> .env
          echo "BANK_PORT=${{ secrets.BANK_PORT }}" >> .env
          echo "GOAL_PORT=${{ secrets.GOAL_PORT }}" >> .env
          echo "DASHBOARD_PORT=${{ secrets.DASHBOARD_PORT }}" >> .env
          echo "AUTH_SERVICE_URL=${{ secrets.AUTH_SERVICE_URL }}" >> .env
          echo "BUDGET_SERVICE_URL=${{ secrets.BUDGET_SERVICE_URL }}" >> .env
          echo "TRANSACTION_SERVICE_URL=${{ secrets.TRANSACTION_SERVICE_URL }}" >> .env
          echo "BANK_SERVICE_URL=${{ secrets.BANK_SERVICE_URL }}" >> .env
          echo "GOAL_SERVICE_URL=${{ secrets.GOAL_SERVICE_URL }}" >> .env
          
          echo "S3_URL=${{ secrets.S3_URL }}" >> .env
          echo "S3_ACCESS_KEY=${{ secrets.S3_ACCESS_KEY }}" >> .env
          echo "S3_SECRET_KEY=${{ secrets.S3_SECRET_KEY }}" >> .env
          echo "S3_BUCKET=${{ secrets.S3_BUCKET }}" >> .env
          echo "S3_PUBLIC_URL_PREFIX=${{ secrets.S3_PUBLIC_URL_PREFIX }}" >> .env
          echo "MINIO_PORT=${{ secrets.MINIO_PORT }}" >> .env
          echo "MINIO_CONSOLE_PORT=${{ secrets.MINIO_CONSOLE_PORT }}" >> .env

      - name: Start Services
        run: docker compose up -d --build

      - name: Wait for Services
        run: sleep 40

      - name: Run Newman Tests
        run: |
          npm install -g newman
          newman run postman/API-SmartBudget.json \
            --env-var "authBaseUrl=http://localhost:${{ secrets.AUTH_PORT }}/api/v1" \
            --reporters cli

      - name: Dump Logs on Failure
        if: failure()
        run: docker compose logs auth_service

      - name: Stop Services
        if: always()
        run: docker compose down